steps:
- script: |
    python -m venv env
    source env/bin/activate
    pip install -r requirements.txt
  displayName: 'Instalar dependencias'

- script: |
    pytest
  displayName: 'Ejecutar pruebas'

