steps:
- script: |
    python -m venv env
    source env/bin/activate
    pip install -r requirements.txt
  displayName: 'Instalar dependencias'

- script: |
    sudo apt-get update
    sudo apt-get install python3-pip -y
    pip3 install pytest
  displayName: 'Instalar pytest'

- script: |
    pytest
  displayName: 'Ejecutar pruebas'
