- script: |
    python -m venv env
    source env/bin/activate
    pip install -r requirements.txt
  displayName: 'Instalar dependencias'

- script: |
    source env/bin/activate
    pip install Flask
  displayName: 'Instalar Flask'

- script: |
    source env/bin/activate
    pytest
  displayName: 'Ejecutar pruebas'
